version: "3"

services:
  app:
    build: .
    environment:
      mongo_host: "mongodb+srv://theta:Gavin17423@modellog.eaconvz.mongodb.net/?retryWrites=true&w=majority"
    ports:
      - "8003:8000"
